version: "3.8"

services:
  # MongoDB Database (for local development)
  mongodb:
    image: mongo:7
    container_name: jobboard-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - mongodb_data:/data/db

  # Backend API (for local development)
  backend:
    build: ./job-board-backend
    container_name: jobboard-backend
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      NODE_ENV: development
      PORT: 5000
      MONGODB_URI: mongodb://admin:password@mongodb:27017/jobboard?authSource=admin
      JWT_SECRET: your-super-secret-jwt-key-change-in-production
      JWT_EXPIRE: 7d
      EMAIL_HOST: smtp.gmail.com
      EMAIL_PORT: 587
      EMAIL_USER: your-email@gmail.com
      EMAIL_PASS: your-app-password
      MAX_FILE_SIZE: 5242880
      UPLOAD_PATH: ./uploads
      CORS_ORIGIN: http://localhost:3000
    depends_on:
      - mongodb
    volumes:
      - backend_uploads:/app/uploads

  # Frontend (for local development)
  frontend:
    build: ./job-board-platform
    container_name: jobboard-frontend
    restart: unless-stopped
    ports:
      - "3000:80"
    environment:
      - VITE_API_BASE_URL=http://localhost:5000/api
    depends_on:
      - backend

volumes:
  mongodb_data:
  backend_uploads:
