services:
  - type: web
    name: jobboard-backend
    env: docker
    plan: free
    dockerfilePath: Dockerfile
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGODB_URI
        value: mongodb+srv://mohamedermilidev_db_user:V9foDcpY5LFefQaY@cluster0.lbcw9nj.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      - key: JWT_SECRET
        value: your-super-secure-jwt-secret-key-change-this-in-production
      - key: JWT_EXPIRE
        value: 7d
      - key: EMAIL_HOST
        value: smtp.gmail.com
      - key: EMAIL_PORT
        value: 587
      - key: EMAIL_USER
        value: mohamedermilidev_db_user
      - key: EMAIL_PASS
        value: V9foDcpY5LFefQaY
      - key: MAX_FILE_SIZE
        value: 5242880
      - key: UPLOAD_PATH
        value: ./uploads
      - key: CORS_ORIGIN
        value: https://your-frontend-app.vercel.app
